
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fletc
 */
public class even_or_odd extends javax.swing.JFrame {
          static int score = 0;
          static int count = 0;
          
          Random r = new Random();
          int randomNum;
          
    /**
     * Creates new form even_or_odd
     */
    public even_or_odd() {
        initComponents();
        randomNum = r.nextInt(100);
        lblNumber.setText(String.valueOf(randomNum));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumber = new javax.swing.JLabel();
        btnodd = new javax.swing.JButton();
        btneven = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumber.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblNumber.setForeground(new java.awt.Color(255, 51, 51));

        btnodd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnodd.setText("ODD");
        btnodd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoddActionPerformed(evt);
            }
        });

        btneven.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btneven.setText("EVEN");
        btneven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SCORE");

        lblScore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnodd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnodd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneven, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevenActionPerformed
        // TODO add your handling code here:
          count = count+1;
        int num = Integer.parseInt(lblNumber.getText());
        if(count==10){
            
        if(num%2==0){
         score = score+1;
         lblScore.setText(String.valueOf(score));
         randomNum = r.nextInt(100);
        }else{
          randomNum = r.nextInt(100);
          lblNumber.setText(String.valueOf(randomNum));
        }
        JOptionPane.showMessageDialog(this, "Your score is: "+score+"/10");
        count=0;
        score=0;
        lblScore.setText("");
        randomNum = r.nextInt(100);
        lblNumber.setText(String.valueOf(randomNum));
        
        }else{
        
            if(num%2==0){
            score = score+1;
            lblScore.setText(String.valueOf(score));
            randomNum = r.nextInt(100);
            lblNumber.setText(String.valueOf(randomNum));
            }else{
            randomNum = r.nextInt(100);
            lblNumber.setText(String.valueOf(randomNum));
            }
        }                                
    }//GEN-LAST:event_btnevenActionPerformed

    private void btnoddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoddActionPerformed
        // TODO add your handling code here:
        count = count+1;
        int num = Integer.parseInt(lblNumber.getText());
        if(count==10){
            
        if(num%2!=0){
         score = score+1;
         lblScore.setText(String.valueOf(score));
         randomNum = r.nextInt(100);
        }else{
          randomNum = r.nextInt(100);
          lblNumber.setText(String.valueOf(randomNum));
        }
        JOptionPane.showMessageDialog(this, "Your score is: "+score+"/10");
        count=0;
        score=0;
        lblScore.setText("");
        randomNum = r.nextInt(100);
        lblNumber.setText(String.valueOf(randomNum));
        
        }else{
        
            if(num%2!=0){
            score = score+1;
            lblScore.setText(String.valueOf(score));
            randomNum = r.nextInt(100);
            lblNumber.setText(String.valueOf(randomNum));
            }else{
            randomNum = r.nextInt(100);
            lblNumber.setText(String.valueOf(randomNum));
            }
        }
    }//GEN-LAST:event_btnoddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(even_or_odd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(even_or_odd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(even_or_odd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(even_or_odd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new even_or_odd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneven;
    private javax.swing.JButton btnodd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
